import type { Locale } from "./publicCopy";

type LocalizedStatus = "DRAFT" | "PUBLISHED" | "ARCHIVED" | "PENDING_PAYMENT" | "CONFIRMED" | "FULFILLED" | "CANCELLED";

type CommerceCopy = {
  shell: { brandPrimary: string; brandSecondary: string; homeAria: string; navAria: string; store: string; builders: string; console: string; customerSignIn: string; cart: string; toggleNav: string; mobileNavAria: string; footer: string; exploreContracts: string };
  store: { eyebrow: string; heroBefore: string; heroEmphasis: string; heroAfter: string; heroBody: string; heroLink: string; collectionEyebrow: string; collectionTitle: string; categoriesAria: string; all: string; searchLabel: string; searchPlaceholder: string; productCount: (count: number) => string; noMatches: string; resetFilters: string; loading: string; emptyEyebrow: string; emptyTitle: string; emptyBody: string; emptyCta: string; promotionNote: string; promotionMeta: string };
  product: { loading: string; unavailable: string; returnToStore: string; allProducts: string; detail: string; finish: string; options: string; color: string; available: (count: number) => string; unavailableCta: string; addToCart: string; inventoryValidated: string; totalsCalculated: string };
  cart: { eyebrow: (count: number) => string; heading: string; emptyTitle: string; emptyBody: string; exploreStore: string; summary: string; promotionCode: string; apply: string; applied: string; subtotal: string; discount: string; shipping: string; shippingNext: string; estimatedTotal: string; checkout: string; paymentNote: string; decrease: (title: string) => string; increase: (title: string) => string; remove: (title: string) => string };
  checkout: { completeEyebrow: string; orderRecorded: (total: string) => string; pendingPayment: string; returnStore: string; eyebrow: string; heading: string; emptyTitle: string; startStore: string; signInTitle: string; signInBody: string; signIn: string; account: string; email: string; shippingMethod: string; standard: string; standardTiming: string; express: string; expressTiming: string; review: string; subtotal: string; discount: string; shipping: string; orderTotal: string; creating: string; createOrder: string };
  dashboard: { loading: string; signInTitle: string; signInBody: string; signIn: string; operations: string; overview: string; catalog: string; orders: string; storefront: string; developer: string; merchantAccount: string; signOut: string };
  admin: { loadingAccount: string; protectedTitle: string; protectedBody: string; signIn: string; accessRequired: string; accessBody: string; returnStore: string; eyebrow: string; heading: string; body: string; viewStore: string; loadingData: string; setupEyebrow: string; setupTitle: string; setupBody: string; initialize: string; publishedProducts: string; openCarts: string; ordersCreated: string; catalogEyebrow: string; catalogTitle: string; newProduct: string; title: string; handle: string; category: string; subtitle: string; description: string; sku: string; variantTitle: string; defaultVariant: string; price: string; inventory: string; placeholders: { title: string; handle: string; category: string; subtitle: string; description: string; sku: string }; save: string; saving: string; cancel: string; savedMessage: string; unableToCreate: string; publish: string; archive: string; view: string; update: string; ordersEyebrow: string; recentOrders: string; emptyOrders: string; developerEyebrow: string; registryTitle: string; readContracts: string; registry: [string, string, string, string, string, string]; status: Record<LocalizedStatus, string> };
  docs: { eyebrow: string; heroBefore: string; heroEmphasis: string; heroBody: string; modules: string; contracts: string; extensions: string; roadmap: string; typedApi: string; currentContracts: string; extensionEyebrow: string; extensionTitle: string; extensionBody: string; roadmapEyebrow: string; roadmapTitle: string; milestoneGraphql: string; milestoneTheme: string; milestonePayments: string; contractLabels: [string, string, string, string]; contractDetails: [string, string, string, string] };
  notFound: { title: string; body: string; detail: string; goHome: string };
  notifications: { added: string; unableToAdd: string; unableToUpdate: string; promotionApplied: string; promotionUnavailable: string };
};

export const commerceCopy: Record<Locale, CommerceCopy> = {
  en: {
    shell: { brandPrimary: "COMMERCE", brandSecondary: "PLATFORM", homeAria: "Commerce home", navAria: "Commerce navigation", store: "Store", builders: "Builders", console: "Merchant console", customerSignIn: "Customer sign in", cart: "Cart", toggleNav: "Toggle navigation", mobileNavAria: "Mobile commerce navigation", footer: "Storefront, operations, and an extension surface in one foundation.", exploreContracts: "Explore builder contracts →" },
    store: { eyebrow: "Storefront starter / theme 01", heroBefore: "Objects for an", heroEmphasis: "intentional", heroAfter: "everyday.", heroBody: "A launch-ready storefront surface connected to your catalog, variants, cart, promotions, orders, and merchant operations from the first day.", heroLink: "Enter the live collection", collectionEyebrow: "Collection / all systems", collectionTitle: "Field notes", categoriesAria: "Product categories", all: "All", searchLabel: "Search products", searchPlaceholder: "Search the collection", productCount: count => `${count} ${count === 1 ? "product" : "products"} shown`, noMatches: "No products match this search yet.", resetFilters: "Clear filters", loading: "Loading catalog…", emptyEyebrow: "Store awaiting catalog", emptyTitle: "Activate your starter catalog from merchant console.", emptyBody: "The storefront renders only published products from the commerce database. Sign in as a merchant, then initialize the starter catalog or create your own products from the console.", emptyCta: "Open merchant console", promotionNote: "WELCOME15 is active in the starter promotion module. Apply it to an eligible cart at checkout.", promotionMeta: "Promotion / server validated" },
    product: { loading: "Loading product…", unavailable: "This product is unavailable.", returnToStore: "Return to store", allProducts: "All products", detail: "product detail", finish: "Finish", options: "Variant details", color: "Color", available: count => `${count} available`, unavailableCta: "Unavailable", addToCart: "Add to cart", inventoryValidated: "Inventory validated at order creation", totalsCalculated: "Promotion and total calculated server-side" },
    cart: { eyebrow: count => `Cart / ${count} ${count === 1 ? "item" : "items"}`, heading: "Your selection", emptyTitle: "Your cart is waiting.", emptyBody: "Add a product from the reference storefront to exercise the catalog-to-order path.", exploreStore: "Explore store", summary: "Order summary", promotionCode: "Promotion code", apply: "Apply", applied: "applied", subtotal: "Subtotal", discount: "Discount", shipping: "Shipping", shippingNext: "Calculated next", estimatedTotal: "Estimated total", checkout: "Continue to checkout", paymentNote: "Payment capture is intentionally deferred in this platform foundation.", decrease: title => `Decrease ${title} quantity`, increase: title => `Increase ${title} quantity`, remove: title => `Remove ${title}` },
    checkout: { completeEyebrow: "Order record created", orderRecorded: total => `Your order total of ${total} has been recorded as`, pendingPayment: "Pending payment", returnStore: "Return to store", eyebrow: "Checkout / order creation", heading: "Review and create order", emptyTitle: "No open cart.", startStore: "Start at the store", signInTitle: "Sign in to create the order record.", signInBody: "The platform uses the authenticated account as the order customer. Guest checkout is a subsequent module.", signIn: "Sign in to checkout", account: "Account", email: "Email", shippingMethod: "Shipping method", standard: "Standard", standardTiming: "3–5 business days", express: "Express", expressTiming: "1–2 business days", review: "Review", subtotal: "Subtotal", discount: "Discount", shipping: "Shipping", orderTotal: "Order total", creating: "Creating order…", createOrder: "Create pending-payment order" },
    dashboard: { loading: "Loading console…", signInTitle: "Sign in to manage your store.", signInBody: "The platform keeps catalog, order, and launch operations behind the authenticated merchant account boundary.", signIn: "Sign in to merchant console", operations: "Merchant operations", overview: "Overview", catalog: "Catalog", orders: "Orders", storefront: "Storefront", developer: "Developer surface", merchantAccount: "Merchant account", signOut: "Sign out" },
    admin: { loadingAccount: "Loading account…", protectedTitle: "Commerce administration is protected.", protectedBody: "Sign in to manage the catalog, review orders, and initialize the explicit reference store.", signIn: "Sign in to console", accessRequired: "Administrator access required.", accessBody: "Your account can place orders; catalog and operational setup are limited to the platform owner.", returnStore: "Return to store", eyebrow: "Store administration", heading: "Commerce control plane", body: "Published catalog, operational orders, active carts, and extension boundaries in one route-aware console.", viewStore: "View storefront", loadingData: "Loading commerce data…", setupEyebrow: "Explicit setup required", setupTitle: "Activate the reference catalog.", setupBody: "This action creates four published products, six variants, and two server-validated promotion codes. It runs once and never overwrites an existing catalog.", initialize: "Initialize catalog", publishedProducts: "Published products", openCarts: "Open carts", ordersCreated: "Orders created", catalogEyebrow: "Catalog operations", catalogTitle: "Products and variants", newProduct: "New product", title: "Title", handle: "Handle", category: "Category", subtitle: "Subtitle", description: "Description", sku: "SKU", variantTitle: "Variant title", defaultVariant: "Default", price: "Price (USD)", inventory: "Inventory", placeholders: { title: "Orbit Clock", handle: "orbit-clock", category: "Objects", subtitle: "Desktop timepiece", description: "A concise product record for the catalog.", sku: "ORBIT-01" }, save: "Save as draft", saving: "Saving…", cancel: "Cancel", savedMessage: "Product saved as draft. Publish it when the storefront record is ready.", unableToCreate: "Unable to create product.", publish: "Publish", archive: "Archive", view: "View", update: "Update", ordersEyebrow: "OMS", recentOrders: "Recent orders", emptyOrders: "Orders appear after an authenticated checkout completes.", developerEyebrow: "Developer surface", registryTitle: "Module registry", readContracts: "Read contracts", registry: ["catalog / published", "cart / server calculated", "checkout / pending payment", "orders / immutable lines", "promotion / threshold guarded", "extensions / typed manifest"], status: { DRAFT: "Draft", PUBLISHED: "Published", ARCHIVED: "Archived", PENDING_PAYMENT: "Pending payment", CONFIRMED: "Confirmed", FULFILLED: "Fulfilled", CANCELLED: "Cancelled" } },
    docs: { eyebrow: "Builder surface / commerce-in-a-box", heroBefore: "Commercial core,", heroEmphasis: "visible contracts.", heroBody: "The platform keeps the server as the commercial source of truth: catalog values are read from persistence; cart totals are recomputed; promotions are validated; orders snapshot line details.", modules: "MODULES", contracts: "Contracts", extensions: "Extensions", roadmap: "Roadmap", typedApi: "Typed API", currentContracts: "Current contracts", extensionEyebrow: "Extension boundary", extensionTitle: "Prefer a manifest to a fork.", extensionBody: "An extension supplies a manifest, module contracts, connector implementation, and contract tests. It must not reach into private tables or mutate core runtime behavior through import side effects.", roadmapEyebrow: "Next engineering milestones", roadmapTitle: "Deliberate expansion path", milestoneGraphql: "GraphQL façade and store API tokens", milestoneTheme: "CMS/theme package and storefront widget registry", milestonePayments: "Payment-provider integration with verified webhooks", contractLabels: ["Catalog", "Cart", "Checkout", "Admin"], contractDetails: ["product + variants", "server-priced lines", "pending-payment order", "role-gated operations"] },
    notFound: { title: "Page not found", body: "Sorry, the page you are looking for does not exist.", detail: "It may have been moved or deleted.", goHome: "Go home" },
    notifications: { added: "Added to cart", unableToAdd: "Unable to add product to cart.", unableToUpdate: "Unable to update cart.", promotionApplied: "Promotion applied", promotionUnavailable: "Promotion unavailable." },
  },
  fr: {
    shell: { brandPrimary: "COMMERCE", brandSecondary: "PLATEFORME", homeAria: "Accueil commerce", navAria: "Navigation commerce", store: "Boutique", builders: "Développeurs", console: "Console marchand", customerSignIn: "Connexion client", cart: "Panier", toggleNav: "Afficher la navigation", mobileNavAria: "Navigation commerce mobile", footer: "Vitrine, opérations et surface d’extension dans une même fondation.", exploreContracts: "Explorer les contrats développeur →" },
    store: { eyebrow: "Vitrine de départ / thème 01", heroBefore: "Des objets pour un", heroEmphasis: "quotidien", heroAfter: "intentionnel.", heroBody: "Une vitrine prête à lancer, connectée dès le premier jour à votre catalogue, variantes, panier, promotions, commandes et opérations marchand.", heroLink: "Entrer dans la collection", collectionEyebrow: "Collection / tous systèmes", collectionTitle: "Notes de terrain", categoriesAria: "Catégories de produits", all: "Tout", searchLabel: "Rechercher des produits", searchPlaceholder: "Rechercher dans la collection", productCount: count => `${count} produit${count === 1 ? "" : "s"} affiché${count === 1 ? "" : "s"}`, noMatches: "Aucun produit ne correspond encore à cette recherche.", resetFilters: "Effacer les filtres", loading: "Chargement du catalogue…", emptyEyebrow: "Boutique en attente de catalogue", emptyTitle: "Activez votre catalogue de départ depuis la console marchand.", emptyBody: "La vitrine affiche uniquement les produits publiés de la base de données commerce. Connectez-vous comme marchand, puis initialisez le catalogue de départ ou créez vos propres produits depuis la console.", emptyCta: "Ouvrir la console marchand", promotionNote: "WELCOME15 est actif dans le module de promotion de départ. Appliquez-le à un panier éligible lors du paiement.", promotionMeta: "Promotion / validée par le serveur" },
    product: { loading: "Chargement du produit…", unavailable: "Ce produit n’est pas disponible.", returnToStore: "Retour à la boutique", allProducts: "Tous les produits", detail: "détail produit", finish: "Finition", options: "Détails de la variante", color: "Couleur", available: count => `${count} disponible${count === 1 ? "" : "s"}`, unavailableCta: "Indisponible", addToCart: "Ajouter au panier", inventoryValidated: "Stock validé lors de la création de la commande", totalsCalculated: "Promotion et total calculés côté serveur" },
    cart: { eyebrow: count => `Panier / ${count} article${count === 1 ? "" : "s"}`, heading: "Votre sélection", emptyTitle: "Votre panier attend.", emptyBody: "Ajoutez un produit de la vitrine de référence pour parcourir le flux du catalogue à la commande.", exploreStore: "Explorer la boutique", summary: "Récapitulatif", promotionCode: "Code promotionnel", apply: "Appliquer", applied: "appliqué", subtotal: "Sous-total", discount: "Remise", shipping: "Livraison", shippingNext: "Calculée ensuite", estimatedTotal: "Total estimé", checkout: "Continuer vers le paiement", paymentNote: "La capture du paiement est volontairement différée dans cette fondation de plateforme.", decrease: title => `Réduire la quantité de ${title}`, increase: title => `Augmenter la quantité de ${title}`, remove: title => `Retirer ${title}` },
    checkout: { completeEyebrow: "Commande enregistrée", orderRecorded: total => `Le total de votre commande, ${total}, a été enregistré comme`, pendingPayment: "Paiement en attente", returnStore: "Retour à la boutique", eyebrow: "Paiement / création de commande", heading: "Vérifier et créer la commande", emptyTitle: "Aucun panier ouvert.", startStore: "Commencer dans la boutique", signInTitle: "Connectez-vous pour créer l’enregistrement de commande.", signInBody: "La plateforme utilise le compte authentifié comme client de la commande. Le paiement invité est un module ultérieur.", signIn: "Se connecter pour payer", account: "Compte", email: "E-mail", shippingMethod: "Mode de livraison", standard: "Standard", standardTiming: "3–5 jours ouvrés", express: "Express", expressTiming: "1–2 jours ouvrés", review: "Vérification", subtotal: "Sous-total", discount: "Remise", shipping: "Livraison", orderTotal: "Total de la commande", creating: "Création de la commande…", createOrder: "Créer une commande en attente de paiement" },
    dashboard: { loading: "Chargement de la console…", signInTitle: "Connectez-vous pour gérer votre boutique.", signInBody: "La plateforme conserve le catalogue, les commandes et les opérations de lancement derrière le compte marchand authentifié.", signIn: "Se connecter à la console marchand", operations: "Opérations marchand", overview: "Aperçu", catalog: "Catalogue", orders: "Commandes", storefront: "Vitrine", developer: "Surface développeur", merchantAccount: "Compte marchand", signOut: "Se déconnecter" },
    admin: { loadingAccount: "Chargement du compte…", protectedTitle: "L’administration commerce est protégée.", protectedBody: "Connectez-vous pour gérer le catalogue, consulter les commandes et initialiser la boutique de référence explicite.", signIn: "Se connecter à la console", accessRequired: "Accès administrateur requis.", accessBody: "Votre compte peut passer des commandes ; la configuration du catalogue et des opérations est limitée au propriétaire de la plateforme.", returnStore: "Retour à la boutique", eyebrow: "Administration boutique", heading: "Poste de contrôle commerce", body: "Catalogue publié, commandes opérationnelles, paniers actifs et limites d’extension dans une console guidée par les routes.", viewStore: "Voir la vitrine", loadingData: "Chargement des données commerce…", setupEyebrow: "Configuration explicite requise", setupTitle: "Activer le catalogue de référence.", setupBody: "Cette action crée quatre produits publiés, six variantes et deux codes promotionnels validés par le serveur. Elle ne s’exécute qu’une fois et n’écrase jamais un catalogue existant.", initialize: "Initialiser le catalogue", publishedProducts: "Produits publiés", openCarts: "Paniers ouverts", ordersCreated: "Commandes créées", catalogEyebrow: "Opérations catalogue", catalogTitle: "Produits et variantes", newProduct: "Nouveau produit", title: "Titre", handle: "Identifiant", category: "Catégorie", subtitle: "Sous-titre", description: "Description", sku: "SKU", variantTitle: "Titre de la variante", defaultVariant: "Par défaut", price: "Prix (USD)", inventory: "Stock", placeholders: { title: "Horloge Orbit", handle: "horloge-orbit", category: "Objets", subtitle: "Horloge de bureau", description: "Une fiche produit concise pour le catalogue.", sku: "ORBIT-01" }, save: "Enregistrer comme brouillon", saving: "Enregistrement…", cancel: "Annuler", savedMessage: "Produit enregistré comme brouillon. Publiez-le lorsque la fiche vitrine est prête.", unableToCreate: "Impossible de créer le produit.", publish: "Publier", archive: "Archiver", view: "Voir", update: "Mettre à jour", ordersEyebrow: "OMS", recentOrders: "Commandes récentes", emptyOrders: "Les commandes apparaissent après un paiement authentifié.", developerEyebrow: "Surface développeur", registryTitle: "Registre des modules", readContracts: "Lire les contrats", registry: ["catalogue / publié", "panier / calculé côté serveur", "paiement / en attente", "commandes / lignes immuables", "promotion / seuil contrôlé", "extensions / manifeste typé"], status: { DRAFT: "Brouillon", PUBLISHED: "Publié", ARCHIVED: "Archivé", PENDING_PAYMENT: "Paiement en attente", CONFIRMED: "Confirmée", FULFILLED: "Exécutée", CANCELLED: "Annulée" } },
    docs: { eyebrow: "Surface développeur / commerce prêt à lancer", heroBefore: "Cœur commercial,", heroEmphasis: "contrats visibles.", heroBody: "La plateforme conserve le serveur comme source de vérité commerciale : les valeurs catalogue viennent de la persistance ; les totaux panier sont recalculés ; les promotions sont validées ; les commandes figent les détails de ligne.", modules: "MODULES", contracts: "Contrats", extensions: "Extensions", roadmap: "Feuille de route", typedApi: "API typée", currentContracts: "Contrats actuels", extensionEyebrow: "Limite d’extension", extensionTitle: "Préférez un manifeste à un fork.", extensionBody: "Une extension fournit un manifeste, des contrats de module, une implémentation de connecteur et des tests de contrat. Elle ne doit pas atteindre les tables privées ni modifier le comportement du cœur via des effets de bord d’import.", roadmapEyebrow: "Prochains jalons d’ingénierie", roadmapTitle: "Parcours d’extension délibéré", milestoneGraphql: "Façade GraphQL et jetons API boutique", milestoneTheme: "Paquet CMS/thème et registre de widgets vitrine", milestonePayments: "Intégration de paiement avec webhooks vérifiés", contractLabels: ["Catalogue", "Panier", "Paiement", "Administration"], contractDetails: ["produit + variantes", "lignes tarifées côté serveur", "commande en attente de paiement", "opérations protégées par rôle"] },
    notFound: { title: "Page introuvable", body: "La page que vous recherchez n’existe pas.", detail: "Elle a peut-être été déplacée ou supprimée.", goHome: "Retour à l’accueil" },
    notifications: { added: "Ajouté au panier", unableToAdd: "Impossible d’ajouter le produit au panier.", unableToUpdate: "Impossible de mettre à jour le panier.", promotionApplied: "Promotion appliquée", promotionUnavailable: "Promotion indisponible." },
  },
  ar: {
    shell: { brandPrimary: "منصة", brandSecondary: "التجارة", homeAria: "الصفحة الرئيسية للتجارة", navAria: "تنقل التجارة", store: "المتجر", builders: "للمطورين", console: "لوحة التاجر", customerSignIn: "دخول العميل", cart: "السلة", toggleNav: "تبديل التنقل", mobileNavAria: "تنقل التجارة على الهاتف", footer: "واجهة متجر وعمليات وسطح للتوسّع في أساس واحد.", exploreContracts: "استكشف عقود المطورين ←" },
    store: { eyebrow: "واجهة متجر جاهزة / قالب 01", heroBefore: "أغراض من أجل يومي", heroEmphasis: "مقصود", heroAfter: ".", heroBody: "واجهة متجر جاهزة للإطلاق ومتصلة منذ اليوم الأول بالكتالوج والخيارات والسلة والعروض والطلبات وعمليات التاجر.", heroLink: "ادخل إلى المجموعة المباشرة", collectionEyebrow: "المجموعة / جميع الأنظمة", collectionTitle: "ملاحظات ميدانية", categoriesAria: "فئات المنتجات", all: "الكل", searchLabel: "البحث عن منتجات", searchPlaceholder: "ابحث في المجموعة", productCount: count => `${count} ${count === 1 ? "منتج معروض" : "منتجات معروضة"}`, noMatches: "لا توجد منتجات مطابقة لهذا البحث بعد.", resetFilters: "مسح عوامل التصفية", loading: "جارٍ تحميل الكتالوج…", emptyEyebrow: "المتجر بانتظار الكتالوج", emptyTitle: "فعّل كتالوج البداية من لوحة التاجر.", emptyBody: "تعرض واجهة المتجر المنتجات المنشورة فقط من قاعدة بيانات التجارة. سجّل الدخول كتاجر، ثم هيّئ كتالوج البداية أو أنشئ منتجاتك الخاصة من اللوحة.", emptyCta: "افتح لوحة التاجر", promotionNote: "رمز WELCOME15 مفعّل في وحدة عروض البداية. طبّقه على سلة مؤهلة عند الدفع.", promotionMeta: "العرض / تم التحقق منه في الخادم" },
    product: { loading: "جارٍ تحميل المنتج…", unavailable: "هذا المنتج غير متاح.", returnToStore: "العودة إلى المتجر", allProducts: "كل المنتجات", detail: "تفاصيل المنتج", finish: "اللمسة النهائية", options: "تفاصيل الخيار", color: "اللون", available: count => `${count} متاح`, unavailableCta: "غير متاح", addToCart: "أضف إلى السلة", inventoryValidated: "يتم التحقق من المخزون عند إنشاء الطلب", totalsCalculated: "يتم احتساب العرض والإجمالي على الخادم" },
    cart: { eyebrow: count => `السلة / ${count} ${count === 1 ? "منتج" : "منتجات"}`, heading: "اختياراتك", emptyTitle: "سلتك بانتظارك.", emptyBody: "أضف منتجًا من واجهة المتجر المرجعية لاختبار المسار من الكتالوج إلى الطلب.", exploreStore: "استكشف المتجر", summary: "ملخص الطلب", promotionCode: "رمز العرض", apply: "تطبيق", applied: "تم تطبيقه", subtotal: "المجموع الفرعي", discount: "الخصم", shipping: "الشحن", shippingNext: "يُحسب لاحقًا", estimatedTotal: "الإجمالي التقديري", checkout: "المتابعة إلى الدفع", paymentNote: "يتم تأجيل تحصيل الدفع عمدًا في أساس المنصة هذا.", decrease: title => `تقليل كمية ${title}`, increase: title => `زيادة كمية ${title}`, remove: title => `إزالة ${title}` },
    checkout: { completeEyebrow: "تم إنشاء سجل الطلب", orderRecorded: total => `تم تسجيل إجمالي طلبك البالغ ${total} بالحالة`, pendingPayment: "بانتظار الدفع", returnStore: "العودة إلى المتجر", eyebrow: "الدفع / إنشاء الطلب", heading: "راجع الطلب وأنشئه", emptyTitle: "لا توجد سلة مفتوحة.", startStore: "ابدأ من المتجر", signInTitle: "سجّل الدخول لإنشاء سجل الطلب.", signInBody: "تستخدم المنصة الحساب المُصادق عليه بصفته عميل الطلب. إتمام الشراء للضيوف وحدة لاحقة.", signIn: "سجّل الدخول للدفع", account: "الحساب", email: "البريد الإلكتروني", shippingMethod: "طريقة الشحن", standard: "عادي", standardTiming: "3–5 أيام عمل", express: "سريع", expressTiming: "1–2 يوم عمل", review: "المراجعة", subtotal: "المجموع الفرعي", discount: "الخصم", shipping: "الشحن", orderTotal: "إجمالي الطلب", creating: "جارٍ إنشاء الطلب…", createOrder: "أنشئ طلبًا بانتظار الدفع" },
    dashboard: { loading: "جارٍ تحميل اللوحة…", signInTitle: "سجّل الدخول لإدارة متجرك.", signInBody: "تُبقي المنصة الكتالوج والطلبات وعمليات الإطلاق خلف حدود حساب التاجر المُصادق عليه.", signIn: "سجّل الدخول إلى لوحة التاجر", operations: "عمليات التاجر", overview: "نظرة عامة", catalog: "الكتالوج", orders: "الطلبات", storefront: "واجهة المتجر", developer: "واجهة المطور", merchantAccount: "حساب التاجر", signOut: "تسجيل الخروج" },
    admin: { loadingAccount: "جارٍ تحميل الحساب…", protectedTitle: "إدارة التجارة محمية.", protectedBody: "سجّل الدخول لإدارة الكتالوج ومراجعة الطلبات وتهيئة المتجر المرجعي الصريح.", signIn: "سجّل الدخول إلى اللوحة", accessRequired: "يتطلب صلاحية مسؤول.", accessBody: "يمكن لحسابك إنشاء الطلبات؛ أما إعداد الكتالوج والعمليات فمقصور على مالك المنصة.", returnStore: "العودة إلى المتجر", eyebrow: "إدارة المتجر", heading: "لوحة تحكم التجارة", body: "كتالوج منشور وطلبات تشغيلية وسلال نشطة وحدود توسعة في لوحة مدركة للمسارات.", viewStore: "عرض واجهة المتجر", loadingData: "جارٍ تحميل بيانات التجارة…", setupEyebrow: "إعداد صريح مطلوب", setupTitle: "فعّل الكتالوج المرجعي.", setupBody: "ينشئ هذا الإجراء أربعة منتجات منشورة وستة خيارات ورمزين للعروض تم التحقق منهما على الخادم. يعمل مرة واحدة ولا يستبدل كتالوجًا قائمًا.", initialize: "تهيئة الكتالوج", publishedProducts: "المنتجات المنشورة", openCarts: "السلال المفتوحة", ordersCreated: "الطلبات المنشأة", catalogEyebrow: "عمليات الكتالوج", catalogTitle: "المنتجات والخيارات", newProduct: "منتج جديد", title: "العنوان", handle: "المعرّف", category: "الفئة", subtitle: "العنوان الفرعي", description: "الوصف", sku: "رمز SKU", variantTitle: "عنوان الخيار", defaultVariant: "افتراضي", price: "السعر (USD)", inventory: "المخزون", placeholders: { title: "ساعة أوربت", handle: "orbit-clock", category: "أغراض", subtitle: "ساعة مكتبية", description: "سجل منتج موجز للكتالوج.", sku: "ORBIT-01" }, save: "حفظ كمسودة", saving: "جارٍ الحفظ…", cancel: "إلغاء", savedMessage: "تم حفظ المنتج كمسودة. انشره عندما تصبح بطاقة واجهة المتجر جاهزة.", unableToCreate: "تعذّر إنشاء المنتج.", publish: "نشر", archive: "أرشفة", view: "عرض", update: "تحديث", ordersEyebrow: "إدارة الطلبات", recentOrders: "أحدث الطلبات", emptyOrders: "تظهر الطلبات بعد اكتمال الدفع المُصادق عليه.", developerEyebrow: "واجهة المطور", registryTitle: "سجل الوحدات", readContracts: "قراءة العقود", registry: ["الكتالوج / منشور", "السلة / محسوبة على الخادم", "الدفع / بانتظار الدفع", "الطلبات / بنود ثابتة", "العرض / عتبة محكومة", "التوسعات / بيان مكتوب"], status: { DRAFT: "مسودة", PUBLISHED: "منشور", ARCHIVED: "مؤرشف", PENDING_PAYMENT: "بانتظار الدفع", CONFIRMED: "مؤكد", FULFILLED: "مُنفذ", CANCELLED: "ملغى" } },
    docs: { eyebrow: "واجهة المطور / تجارة جاهزة للإطلاق", heroBefore: "نواة تجارية،", heroEmphasis: "عقود واضحة.", heroBody: "تُبقي المنصة الخادم مصدر الحقيقة التجارية: تُقرأ قيم الكتالوج من التخزين؛ ويُعاد حساب إجماليات السلة؛ وتُتحقق العروض؛ وتحتفظ الطلبات بتفاصيل البنود.", modules: "الوحدات", contracts: "العقود", extensions: "التوسعات", roadmap: "خارطة الطريق", typedApi: "واجهة API مكتوبة", currentContracts: "العقود الحالية", extensionEyebrow: "حدود التوسعة", extensionTitle: "فضّل بيانًا على تشعب الكود.", extensionBody: "توفر التوسعة بيانًا وعقود وحدات وتنفيذ موصل واختبارات للعقود. لا يجوز لها الوصول إلى الجداول الخاصة أو تغيير سلوك النواة عبر آثار جانبية للاستيراد.", roadmapEyebrow: "محطات الهندسة القادمة", roadmapTitle: "مسار توسعة مقصود", milestoneGraphql: "واجهة GraphQL ورموز API للمتجر", milestoneTheme: "حزمة CMS/قالب وسجل ودجات واجهة المتجر", milestonePayments: "ربط موفر الدفع مع webhooks موثقة", contractLabels: ["الكتالوج", "السلة", "الدفع", "الإدارة"], contractDetails: ["المنتج + الخيارات", "بنود مسعّرة على الخادم", "طلب بانتظار الدفع", "عمليات محكومة بالدور"] },
    notFound: { title: "الصفحة غير موجودة", body: "الصفحة التي تبحث عنها غير موجودة.", detail: "ربما تم نقلها أو حذفها.", goHome: "العودة للرئيسية" },
    notifications: { added: "تمت الإضافة إلى السلة", unableToAdd: "تعذّر إضافة المنتج إلى السلة.", unableToUpdate: "تعذّر تحديث السلة.", promotionApplied: "تم تطبيق العرض", promotionUnavailable: "العرض غير متاح." },
  },
};

export function translateProductStatus(locale: Locale, status: LocalizedStatus) {
  return commerceCopy[locale].admin.status[status];
}
