import type { Locale } from "./publicCopy";

type WorkspaceCopy = {
  signInTitle: string; signInBody: string; signIn: string; loading: string;
  nav: { overview: string; catalog: string; orders: string; marketing: string; studio: string; extensions: string; storefront: string; signOut: string };
  onboarding: { eyebrow: string; title: string; body: string; workspace: string; store: string; handle: string; action: string; creating: string };
  overview: { eyebrow: string; title: string; body: string; storeState: string; theme: string; pages: string; extensions: string; route: string; studioAction: string; catalogAction: string };
  catalog: { eyebrow: string; title: string; body: string; product: string; selectedProduct: (variants: number, stock: number) => string; status: string; inventory: string; price: string; create: string; publish: string; archive: string; draft: string; addTitle: string; addHandle: string; addPrice: string; addStock: string; addAction: string; creating: string; media: string; upload: string; uploading: string; gallery: string; hover: string; focalX: string; focalY: string; saveCrop: string; remove: string; noMedia: string; imageAlt: string; moveEarlier: string; moveLater: string; mediaFor: string; productGallery: string; bulkUpload: string; optimizing: string; uploadResult: string; variants: string; color: string; saveVariant: string; savingVariant: string; combinationTitle: string; combinationHelp: string; optionGroups: string; skuPrefix: string; openingStock: string; lowStockAlert: string; generateVariants: string; generatingVariants: string; invalidOptionGroups: string; combinationCreated: string; combinationsSkipped: string };
  orders: { eyebrow: string; title: string; body: string; number: string; status: string; customer: string; total: string; empty: string };
  marketing: { eyebrow: string; title: string; body: string; enabled: string; disabled: string; activate: string; pause: string; note: string };
  handoff: { eyebrow: string; title: string; body: string; create: string; label: string; creating: string; shared: string; approved: string; draft: string; review: string; markApproved: string; note: string };
  studio: { eyebrow: string; title: string; body: string; presets: string; sections: string; desktop: string; mobile: string; active: string; visible: string; hidden: string; saveState: string; publish: string; themes: Record<"EDITORIAL" | "STUDIO" | "MONO", { name: string; body: string }> };
  extensions: { eyebrow: string; title: string; body: string; enabled: string; disabled: string; enable: string; disable: string };
};

export const workspaceCopy: Record<Locale, WorkspaceCopy> = {
  en: {
    signInTitle: "Build from a merchant workspace.", signInBody: "Sign in to create your store, shape a real storefront, and operate the commerce layer behind it.", signIn: "Sign in", loading: "Loading merchant workspace…",
    nav: { overview: "Overview", catalog: "Catalog", orders: "Orders", marketing: "Marketing", studio: "Storefront studio", extensions: "Extensions", storefront: "View store", signOut: "Sign out" },
    onboarding: { eyebrow: "Merchant onboarding", title: "Create the operating space behind your next storefront.", body: "This establishes your workspace, the first merchant store, an owner role, a theme, homepage sections, and a deliberate extension registry.", workspace: "Workspace name", store: "Store name", handle: "Store handle", action: "Create merchant workspace", creating: "Creating workspace…" },
    overview: { eyebrow: "Merchant workspace", title: "A real store starts with an operating surface.", body: "Your store owns its visual system, homepage configuration, extensions, catalogue and order operations. Nothing here is a disconnected mock screen.", storeState: "Store state", theme: "Active theme", pages: "Storefront pages", extensions: "Extensions", route: "Store route", studioAction: "Open storefront studio", catalogAction: "Open live store" },
    catalog: { eyebrow: "Store catalog", title: "Merchandise the store your customer can actually buy from.", body: "Products and inventory are scoped to this merchant store. Publishing changes the same catalog rendered by the public storefront.", product: "Product", selectedProduct: (variants, stock) => `${variants} ${variants === 1 ? "variant" : "variants"} · ${stock} units in stock`, status: "Status", inventory: "Inventory", price: "Price", create: "Add product", publish: "Publish", archive: "Archive", draft: "Draft", addTitle: "Product title", addHandle: "Product handle", addPrice: "Price in USD", addStock: "Available inventory", addAction: "Create draft", creating: "Creating draft…", media: "Product media", upload: "Upload image", uploading: "Uploading…", gallery: "Gallery", hover: "Hover media", focalX: "Focal X", focalY: "Focal Y", saveCrop: "Save crop", remove: "Remove", noMedia: "No media yet", imageAlt: "Image description", moveEarlier: "Move earlier", moveLater: "Move later", mediaFor: "Media for", productGallery: "Product gallery", bulkUpload: "Bulk upload", optimizing: "Optimizing images…", uploadResult: "Optimized upload complete", variants: "Variants", color: "Color", saveVariant: "Save variant", savingVariant: "Saving variant…", combinationTitle: "Option combinations", combinationHelp: "Create up to 64 additional variants. Use one group per line: Color: Orange, Lemon", optionGroups: "Option groups", skuPrefix: "SKU prefix", openingStock: "Opening stock", lowStockAlert: "Low-stock alert", generateVariants: "Generate variants", generatingVariants: "Generating…", invalidOptionGroups: "Use one option group per line, for example: Color: Orange, Lemon", combinationCreated: "variant combinations created", combinationsSkipped: "already existed" },
    orders: { eyebrow: "Order operations", title: "See the records created by this storefront.", body: "Orders are immutable commerce records scoped to this merchant store. Payment capture remains intentionally separate from this platform foundation.", number: "Order", status: "Status", customer: "Customer", total: "Total", empty: "Orders appear here after an authenticated customer creates one." },
    marketing: { eyebrow: "Marketing operations", title: "Turn storefront attention into a considered customer record.", body: "Campaign capture and measurement are real store-scoped extension boundaries. Activate only what your team has configured.", enabled: "Active", disabled: "Paused", activate: "Activate", pause: "Pause", note: "A provider connection is deliberately not implied until it is configured." },
    handoff: { eyebrow: "Agency handoff", title: "Create a clean review surface for the client behind this storefront.", body: "A review link exposes the current theme, visible sections, and published catalogue without handing over merchant controls.", create: "Create client review", label: "Review label", creating: "Creating review…", shared: "Shared", approved: "Approved", draft: "Draft", review: "Open review", markApproved: "Mark approved", note: "Review links are intentional presentation artifacts, not public customer checkout links." },
    studio: { eyebrow: "Storefront studio", title: "Make the storefront into a system your team can edit.", body: "Select a preset and alter the actual homepage sections. The preview shares the configuration saved to your merchant store.", presets: "Visual presets", sections: "Homepage sections", desktop: "Desktop preview", mobile: "Mobile preview", active: "Active", visible: "Visible", hidden: "Hidden", saveState: "Changes save to the merchant store", publish: "Publish storefront", themes: { EDITORIAL: { name: "Editorial", body: "Paper, ink and a warm signal for a considered merchandise story." }, STUDIO: { name: "Studio", body: "A clear blue system for fast campaign movement and product clarity." }, MONO: { name: "Mono", body: "A restrained neutral surface for utility-led collections." } } },
    extensions: { eyebrow: "Extension registry", title: "Activate capability without making the core unreadable.", body: "These store-level configurations are persisted with the merchant store. They describe available integration boundaries; they do not imply an unconfigured third-party service is live.", enabled: "Enabled", disabled: "Disabled", enable: "Enable", disable: "Disable" },
  },
  fr: {
    signInTitle: "Construisez depuis un espace marchand.", signInBody: "Connectez-vous pour créer votre boutique, façonner une vraie vitrine et opérer la couche commerce qui la soutient.", signIn: "Se connecter", loading: "Chargement de l’espace marchand…",
    nav: { overview: "Vue d’ensemble", catalog: "Catalogue", orders: "Commandes", marketing: "Marketing", studio: "Studio vitrine", extensions: "Extensions", storefront: "Voir la boutique", signOut: "Se déconnecter" },
    onboarding: { eyebrow: "Onboarding marchand", title: "Créez l’espace opérationnel derrière votre prochaine vitrine.", body: "Cette étape établit votre espace, la première boutique, un rôle propriétaire, un thème, des sections d’accueil et un registre d’extensions délibéré.", workspace: "Nom de l’espace", store: "Nom de la boutique", handle: "Identifiant boutique", action: "Créer l’espace marchand", creating: "Création de l’espace…" },
    overview: { eyebrow: "Espace marchand", title: "Une vraie boutique commence par une surface opérationnelle.", body: "Votre boutique possède son système visuel, sa configuration d’accueil, ses extensions, son catalogue et ses opérations de commande. Aucun écran ici n’est une maquette isolée.", storeState: "État boutique", theme: "Thème actif", pages: "Pages vitrine", extensions: "Extensions", route: "Route boutique", studioAction: "Ouvrir le studio vitrine", catalogAction: "Ouvrir la boutique" },
    catalog: { eyebrow: "Catalogue boutique", title: "Gérez les produits que votre client peut réellement acheter.", body: "Les produits et le stock appartiennent à cette boutique. La publication modifie le catalogue rendu dans la vitrine publique.", product: "Produit", selectedProduct: (variants, stock) => `${variants} variante${variants === 1 ? "" : "s"} · ${stock} unités en stock`, status: "Statut", inventory: "Stock", price: "Prix", create: "Ajouter un produit", publish: "Publier", archive: "Archiver", draft: "Brouillon", addTitle: "Titre du produit", addHandle: "Identifiant produit", addPrice: "Prix en USD", addStock: "Stock disponible", addAction: "Créer un brouillon", creating: "Création du brouillon…", media: "Médias produit", upload: "Importer une image", uploading: "Importation…", gallery: "Galerie", hover: "Média au survol", focalX: "Focale X", focalY: "Focale Y", saveCrop: "Enregistrer le cadrage", remove: "Supprimer", noMedia: "Aucun média", imageAlt: "Description de l’image", moveEarlier: "Avancer", moveLater: "Reculer", mediaFor: "Médias pour", productGallery: "Galerie produit", bulkUpload: "Import multiple", optimizing: "Optimisation des images…", uploadResult: "Import optimisé terminé", variants: "Variantes", color: "Couleur", saveVariant: "Enregistrer la variante", savingVariant: "Enregistrement…", combinationTitle: "Combinaisons d’options", combinationHelp: "Créez jusqu’à 64 variantes supplémentaires. Un groupe par ligne : Couleur : Orange, Citron", optionGroups: "Groupes d’options", skuPrefix: "Préfixe SKU", openingStock: "Stock initial", lowStockAlert: "Alerte stock bas", generateVariants: "Générer les variantes", generatingVariants: "Génération…", invalidOptionGroups: "Utilisez un groupe d’options par ligne, par exemple : Couleur : Orange, Citron", combinationCreated: "combinaisons de variantes créées", combinationsSkipped: "existaient déjà" },
    orders: { eyebrow: "Opérations commandes", title: "Consultez les enregistrements créés par cette vitrine.", body: "Les commandes sont des enregistrements commerce immuables appartenant à cette boutique. La capture de paiement reste séparée de cette fondation plateforme.", number: "Commande", status: "Statut", customer: "Client", total: "Total", empty: "Les commandes apparaissent ici après une création par un client authentifié." },
    marketing: { eyebrow: "Opérations marketing", title: "Transformez l’attention portée à la vitrine en fiche client réfléchie.", body: "La capture de campagne et la mesure sont de vraies limites d’extension propres à la boutique. Activez uniquement ce que votre équipe a configuré.", enabled: "Actif", disabled: "En pause", activate: "Activer", pause: "Mettre en pause", note: "Une connexion fournisseur n’est délibérément pas supposée avant sa configuration." },
    handoff: { eyebrow: "Transmission agence", title: "Créez une surface de revue claire pour le client derrière cette vitrine.", body: "Un lien de revue expose le thème actuel, les sections visibles et le catalogue publié sans donner les contrôles marchand.", create: "Créer une revue client", label: "Libellé de revue", creating: "Création de la revue…", shared: "Partagée", approved: "Approuvée", draft: "Brouillon", review: "Ouvrir la revue", markApproved: "Marquer approuvée", note: "Les liens de revue sont des artefacts de présentation volontaires, pas des liens de paiement client publics." },
    studio: { eyebrow: "Studio vitrine", title: "Faites de la vitrine un système modifiable par l’équipe.", body: "Choisissez un préréglage et modifiez les vraies sections d’accueil. L’aperçu partage la configuration enregistrée avec votre boutique.", presets: "Préréglages visuels", sections: "Sections accueil", desktop: "Aperçu ordinateur", mobile: "Aperçu mobile", active: "Actif", visible: "Visible", hidden: "Masqué", saveState: "Les changements sont enregistrés dans la boutique", publish: "Publier la vitrine", themes: { EDITORIAL: { name: "Éditorial", body: "Papier, encre et signal chaleureux pour un récit marchand réfléchi." }, STUDIO: { name: "Studio", body: "Un système bleu clair pour les campagnes rapides et la lisibilité produit." }, MONO: { name: "Mono", body: "Une surface neutre retenue pour les collections utilitaires." } } },
    extensions: { eyebrow: "Registre d’extensions", title: "Activez une capacité sans rendre le cœur illisible.", body: "Ces configurations sont enregistrées avec la boutique du marchand. Elles décrivent des frontières d’intégration disponibles ; elles ne prétendent pas qu’un service tiers est actif sans configuration.", enabled: "Activé", disabled: "Désactivé", enable: "Activer", disable: "Désactiver" },
  },
  ar: {
    signInTitle: "ابنِ من مساحة تاجر.", signInBody: "سجّل الدخول لإنشاء متجرك وتشكيل واجهة حقيقية وإدارة طبقة التجارة التي تقف خلفها.", signIn: "تسجيل الدخول", loading: "جارٍ تحميل مساحة التاجر…",
    nav: { overview: "نظرة عامة", catalog: "الكتالوج", orders: "الطلبات", marketing: "التسويق", studio: "استوديو المتجر", extensions: "التوسعات", storefront: "عرض المتجر", signOut: "تسجيل الخروج" },
    onboarding: { eyebrow: "إعداد التاجر", title: "أنشئ المساحة التشغيلية خلف واجهة متجرك التالية.", body: "تنشئ هذه الخطوة مساحتك وأول متجر ودور المالك والسمة وأقسام الصفحة الرئيسية وسجل التوسعات المدروس.", workspace: "اسم المساحة", store: "اسم المتجر", handle: "معرّف المتجر", action: "أنشئ مساحة التاجر", creating: "جارٍ إنشاء المساحة…" },
    overview: { eyebrow: "مساحة التاجر", title: "يبدأ المتجر الحقيقي بسطح تشغيلي.", body: "يمتلك متجرك نظامه المرئي وإعداد الصفحة الرئيسية وتوسعاته وكتالوجه وعمليات الطلب. لا توجد هنا شاشات نماذج منفصلة.", storeState: "حالة المتجر", theme: "السمة النشطة", pages: "صفحات الواجهة", extensions: "التوسعات", route: "مسار المتجر", studioAction: "افتح استوديو المتجر", catalogAction: "افتح المتجر" },
    catalog: { eyebrow: "كتالوج المتجر", title: "أدر المنتجات التي يستطيع العميل شراءها فعلًا.", body: "المنتجات والمخزون ضمن هذا المتجر. يغيّر النشر الكتالوج المعروض في واجهة المتجر العامة.", product: "المنتج", selectedProduct: (variants, stock) => `${variants} ${variants === 1 ? "متغير" : "متغيرات"} · ${stock} وحدات في المخزون`, status: "الحالة", inventory: "المخزون", price: "السعر", create: "أضف منتجًا", publish: "نشر", archive: "أرشفة", draft: "مسودة", addTitle: "عنوان المنتج", addHandle: "معرّف المنتج", addPrice: "السعر بالدولار", addStock: "المخزون المتاح", addAction: "أنشئ مسودة", creating: "جارٍ إنشاء المسودة…", media: "وسائط المنتج", upload: "رفع صورة", uploading: "جارٍ الرفع…", gallery: "المعرض", hover: "وسيط التحويم", focalX: "نقطة التركيز س", focalY: "نقطة التركيز ص", saveCrop: "حفظ الاقتصاص", remove: "إزالة", noMedia: "لا توجد وسائط بعد", imageAlt: "وصف الصورة", moveEarlier: "نقل للأمام", moveLater: "نقل للخلف", mediaFor: "الوسائط لـ", productGallery: "معرض المنتج", bulkUpload: "رفع جماعي", optimizing: "جارٍ تحسين الصور…", uploadResult: "اكتمل الرفع المحسّن", variants: "المتغيرات", color: "اللون", saveVariant: "حفظ المتغير", savingVariant: "جارٍ حفظ المتغير…", combinationTitle: "تركيبات الخيارات", combinationHelp: "أنشئ حتى 64 متغيراً إضافياً. استخدم مجموعة واحدة في كل سطر: اللون: برتقالي، ليموني", optionGroups: "مجموعات الخيارات", skuPrefix: "بادئة SKU", openingStock: "المخزون الافتتاحي", lowStockAlert: "تنبيه انخفاض المخزون", generateVariants: "إنشاء المتغيرات", generatingVariants: "جارٍ الإنشاء…", invalidOptionGroups: "استخدم مجموعة خيارات واحدة في كل سطر، مثلاً: اللون: برتقالي، ليموني", combinationCreated: "تركيبات متغيرات تم إنشاؤها", combinationsSkipped: "موجودة مسبقاً" },
    orders: { eyebrow: "عمليات الطلبات", title: "اطّلع على السجلات التي أنشأتها واجهة المتجر هذه.", body: "الطلبات سجلات تجارة غير قابلة للتعديل وضمن هذا المتجر. يبقى تحصيل الدفع منفصلًا عمدًا عن أساس المنصة.", number: "الطلب", status: "الحالة", customer: "العميل", total: "الإجمالي", empty: "تظهر الطلبات هنا بعد أن ينشئها عميل مُصادق عليه." },
    marketing: { eyebrow: "عمليات التسويق", title: "حوّل اهتمام واجهة المتجر إلى سجل عميل مدروس.", body: "التقاط الحملات والقياس حدود توسعة حقيقية ضمن المتجر. فعّل فقط ما أعدّه فريقك.", enabled: "نشط", disabled: "متوقف", activate: "تفعيل", pause: "إيقاف", note: "لا يُفترض اتصال موفّر قبل إعداده عمدًا." },
    handoff: { eyebrow: "تسليم الوكالة", title: "أنشئ سطح مراجعة واضحًا للعميل خلف واجهة المتجر هذه.", body: "يعرض رابط المراجعة السمة الحالية والأقسام الظاهرة والكتالوج المنشور من دون منح أدوات التاجر.", create: "أنشئ مراجعة العميل", label: "اسم المراجعة", creating: "جارٍ إنشاء المراجعة…", shared: "مشارك", approved: "معتمد", draft: "مسودة", review: "افتح المراجعة", markApproved: "عيّنها معتمدة", note: "روابط المراجعة مواد عرض مقصودة وليست روابط دفع عامة للعملاء." },
    studio: { eyebrow: "استوديو واجهة المتجر", title: "اجعل الواجهة نظامًا يستطيع فريقك تعديله.", body: "اختر إعدادًا مرئيًا وعدّل أقسام الصفحة الرئيسية الفعلية. تشترك المعاينة في الإعداد المحفوظ مع متجرك.", presets: "إعدادات مرئية", sections: "أقسام الصفحة الرئيسية", desktop: "معاينة الحاسوب", mobile: "معاينة الهاتف", active: "نشط", visible: "ظاهر", hidden: "مخفي", saveState: "تُحفظ التغييرات في متجر التاجر", publish: "انشر واجهة المتجر", themes: { EDITORIAL: { name: "تحريري", body: "ورق وحبر وإشارة دافئة لقصة منتجات مدروسة." }, STUDIO: { name: "استوديو", body: "نظام أزرق واضح للحملات السريعة ووضوح المنتج." }, MONO: { name: "أحادي", body: "سطح محايد هادئ للمجموعات العملية." } } },
    extensions: { eyebrow: "سجل التوسعات", title: "فعّل القدرة من دون جعل النواة غير مقروءة.", body: "تُحفظ هذه الإعدادات على مستوى متجر التاجر. تصف حدود التكامل المتاحة ولا تدّعي أن خدمة خارجية غير مضبوطة تعمل.", enabled: "مفعّل", disabled: "معطّل", enable: "تفعيل", disable: "تعطيل" },
  },
};
