import {
  addCartLineInputSchema,
  adminCreateProductInputSchema,
  adminSubscriptionInvoiceCreateInputSchema,
  adminSubscriptionInvoiceReviewInputSchema,
  adminInventoryInputSchema,
  adminPrivacyRequestResolutionInputSchema,
  adminProductStatusInputSchema,
  cartQuantityInputSchema,
  customerAddressDeleteInputSchema,
  customerPrivacyErasureInputSchema,
  customerSavedAddressInputSchema,
  customerReturnRequestInputSchema,
  customerMarketingPreferenceInputSchema,
  checkoutInputSchema,
  merchantBootstrapInputSchema,
  merchantCommercialSettingsInputSchema,
  merchantDataPolicyInputSchema,
  merchantDashboardPreferenceInputSchema,
  merchantDeliveryRateInputSchema,
  merchantOrderCancellationInputSchema,
  merchantPaymentReviewInputSchema,
  merchantRefundInputSchema,
  merchantRefundResolutionInputSchema,
  merchantReturnDecisionInputSchema,
  merchantShipmentInputSchema,
  merchantShipmentStatusInputSchema,
  merchantTaxRateInputSchema,
  merchantCatalogCsvImportInputSchema,
  merchantExtensionInputSchema,
  merchantHandoffInputSchema,
  merchantHandoffStatusInputSchema,
  merchantProductMediaBulkUploadInputSchema,
  merchantProductMediaDeleteInputSchema,
  merchantProductMediaUpdateInputSchema,
  merchantProductMediaUploadInputSchema,
  merchantPaymentProviderInputSchema,
  merchantVariantUpdateInputSchema,
  merchantVariantCombinationInputSchema,
  merchantPublishInputSchema,
  merchantSectionInputSchema,
  merchantSeoInputSchema,
  merchantSubscriptionInvoiceReferenceInputSchema,
  merchantThemeInputSchema,
  promotionInputSchema,
  storefrontCheckoutInputSchema,
} from "@shared/commerce";
import { z } from "zod";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "../_core/trpc";
import {
  addCartLine,
  applyPromotion,
  claimCustomerAccount,
  deleteCustomerSavedAddress,
  exportCustomerPrivacyData,
  listAdminPrivacyRequests,
  updateCustomerMarketingConsent,
  createCart,
  createCommerceProduct,
  createMerchantProduct,
  bulkUploadMerchantProductMedia,
  deleteMerchantProductMedia,
  createOrder,
  getCart,
  getCommerceAdminOverview,
  getCustomerOrders,
  getCustomerSavedAddresses,
  getStoreProduct,
  initializeCommerceDemoCatalog,
  importMerchantCatalogCsv,
  listStoreProducts,
  setCommerceProductStatus,
  setMerchantProductStatus,
  setMerchantVariantInventory,
  updateMerchantProductMedia,
  updateMerchantVariant,
  generateMerchantVariantCombinations,
  upsertCustomerSavedAddress,
  requestCustomerPrivacyErasure,
  resolveAdminPrivacyRequest,
  uploadMerchantProductMedia,
  setCommerceVariantInventory,
  updateCartLine,
} from "./service";
import { bootstrapMerchantStore, createStoreHandoff, getMerchantWorkspace, getPublicHandoff, getPublicStorefront, publishStorefront, updateDashboardPreference, updateExtensionStatus, updatePageSection, updateStoreDataPolicy, updateStoreHandoffStatus, updateStoreSeo, updateStoreTheme } from "./workspace";
import { cancelMerchantOrder, createAdminSubscriptionInvoice, createMerchantRefund, createMerchantShipment, createStorefrontCheckout, getMerchantOperationsMonitoring, getStorefrontCheckoutSetup, listMerchantOrderOperations, listMerchantSubscriptionInvoices, requestCustomerReturn, reviewAdminSubscriptionInvoice, resolveMerchantRefund, resolveMerchantReturn, reviewMerchantPayment, submitMerchantSubscriptionInvoiceReference, updateCommercialSettings, updateMerchantPaymentProvider, updateMerchantShipmentStatus, upsertMerchantDeliveryRate, upsertMerchantTaxRate } from "./commercial";

export const commerceRouter = router({
  listProducts: publicProcedure.input(z.object({ category: z.string().optional() }).optional()).query(({ input }) => listStoreProducts(input?.category)),
  getProduct: publicProcedure.input(z.object({ handle: z.string().min(1) })).query(({ input }) => getStoreProduct(input.handle)),
  createCart: publicProcedure.input(z.object({ sessionKey: z.string().min(8).max(128), storeId: z.string().min(3).max(64).optional() })).mutation(({ input }) => createCart(input.sessionKey, input.storeId)),
  getCart: publicProcedure.input(z.object({ cartId: z.string().min(8).max(64) })).query(({ input }) => getCart(input.cartId)),
  addCartLine: publicProcedure.input(addCartLineInputSchema).mutation(({ input }) => addCartLine(input)),
  updateCartLine: publicProcedure.input(cartQuantityInputSchema).mutation(({ input }) => updateCartLine(input)),
  applyPromotion: publicProcedure.input(promotionInputSchema).mutation(({ input }) => applyPromotion(input.cartId, input.code)),
  checkoutSetup: publicProcedure.input(z.object({ cartId: z.string().min(8).max(64) })).query(({ input }) => getStorefrontCheckoutSetup(input.cartId)),
  storefrontCheckout: publicProcedure.input(storefrontCheckoutInputSchema).mutation(({ input }) => createStorefrontCheckout(input)),
  checkout: protectedProcedure.input(checkoutInputSchema).mutation(({ ctx, input }) => createOrder({ ...input, customerId: ctx.user.id })),
  myOrders: protectedProcedure.query(({ ctx }) => getCustomerOrders(ctx.user.id)),
  claimCustomerAccount: protectedProcedure.mutation(({ ctx }) => claimCustomerAccount(ctx.user.id)),
  requestReturn: protectedProcedure.input(customerReturnRequestInputSchema).mutation(({ ctx, input }) => requestCustomerReturn({ userId: ctx.user.id, ...input })),
  updateMarketingPreference: protectedProcedure.input(customerMarketingPreferenceInputSchema).mutation(({ ctx, input }) => updateCustomerMarketingConsent(ctx.user.id, input.enabled)),
  myAddresses: protectedProcedure.query(({ ctx }) => getCustomerSavedAddresses(ctx.user.id)),
  upsertAddress: protectedProcedure.input(customerSavedAddressInputSchema).mutation(({ ctx, input }) => upsertCustomerSavedAddress(ctx.user.id, input)),
  deleteAddress: protectedProcedure.input(customerAddressDeleteInputSchema).mutation(({ ctx, input }) => deleteCustomerSavedAddress(ctx.user.id, input.addressId)),
  exportMyData: protectedProcedure.query(({ ctx }) => exportCustomerPrivacyData(ctx.user.id)),
  requestErasure: protectedProcedure.input(customerPrivacyErasureInputSchema).mutation(({ ctx, input }) => requestCustomerPrivacyErasure(ctx.user.id, input.note)),
  adminOverview: adminProcedure.query(() => getCommerceAdminOverview()),
  initializeDemoCatalog: adminProcedure.mutation(({ ctx }) => initializeCommerceDemoCatalog(ctx.user.id)),
  adminCreateSubscriptionInvoice: adminProcedure.input(adminSubscriptionInvoiceCreateInputSchema).mutation(({ input }) => createAdminSubscriptionInvoice(input)),
  adminReviewSubscriptionInvoice: adminProcedure.input(adminSubscriptionInvoiceReviewInputSchema).mutation(({ input }) => reviewAdminSubscriptionInvoice(input)),
  adminPrivacyRequests: adminProcedure.query(() => listAdminPrivacyRequests()),
  adminResolvePrivacyRequest: adminProcedure.input(adminPrivacyRequestResolutionInputSchema).mutation(({ input }) => resolveAdminPrivacyRequest(input)),
  createProduct: adminProcedure.input(adminCreateProductInputSchema).mutation(({ ctx, input }) => createCommerceProduct(ctx.user.id, input)),
  setProductStatus: adminProcedure.input(adminProductStatusInputSchema).mutation(({ input }) => setCommerceProductStatus(input.productId, input.status)),
  setVariantInventory: adminProcedure.input(adminInventoryInputSchema).mutation(({ input }) => setCommerceVariantInventory(input.variantId, input.inventoryQty)),
  publicStorefront: publicProcedure.input(z.object({ handle: z.string().min(3).max(128) })).query(({ input }) => getPublicStorefront(input.handle)),
  publicHandoff: publicProcedure.input(z.object({ token: z.string().min(8).max(64) })).query(({ input }) => getPublicHandoff(input.token)),
  workspace: router({
    mine: protectedProcedure.query(({ ctx }) => getMerchantWorkspace(ctx.user.id)),
    bootstrap: protectedProcedure.input(merchantBootstrapInputSchema).mutation(({ ctx, input }) => bootstrapMerchantStore({ userId: ctx.user.id, userName: ctx.user.name, ...input })),
    updateTheme: protectedProcedure.input(merchantThemeInputSchema).mutation(({ ctx, input }) => updateStoreTheme({ userId: ctx.user.id, ...input })),
    updateSeo: protectedProcedure.input(merchantSeoInputSchema).mutation(({ ctx, input }) => updateStoreSeo({ userId: ctx.user.id, ...input })),
    updateDataPolicy: protectedProcedure.input(merchantDataPolicyInputSchema).mutation(({ ctx, input }) => updateStoreDataPolicy({ userId: ctx.user.id, ...input })),
    updateSection: protectedProcedure.input(merchantSectionInputSchema).mutation(({ ctx, input }) => updatePageSection({ userId: ctx.user.id, ...input })),
    updateExtension: protectedProcedure.input(merchantExtensionInputSchema).mutation(({ ctx, input }) => updateExtensionStatus({ userId: ctx.user.id, ...input })),
    updateDashboardPreference: protectedProcedure.input(merchantDashboardPreferenceInputSchema).mutation(({ ctx, input }) => updateDashboardPreference({ userId: ctx.user.id, ...input })),
    createHandoff: protectedProcedure.input(merchantHandoffInputSchema).mutation(({ ctx, input }) => createStoreHandoff({ userId: ctx.user.id, ...input })),
    updateHandoffStatus: protectedProcedure.input(merchantHandoffStatusInputSchema).mutation(({ ctx, input }) => updateStoreHandoffStatus({ userId: ctx.user.id, ...input })),
    publish: protectedProcedure.input(merchantPublishInputSchema).mutation(({ ctx, input }) => publishStorefront({ userId: ctx.user.id, ...input })),
    operations: router({
      overview: protectedProcedure.query(async ({ ctx }) => {
        const workspace = await getMerchantWorkspace(ctx.user.id);
        if (!workspace) throw new Error("Create a merchant workspace first.");
        return getCommerceAdminOverview(workspace.store.id);
      }),
      createProduct: protectedProcedure.input(adminCreateProductInputSchema).mutation(({ ctx, input }) => createMerchantProduct(ctx.user.id, input)),
      setProductStatus: protectedProcedure.input(adminProductStatusInputSchema).mutation(({ ctx, input }) => setMerchantProductStatus(ctx.user.id, input.productId, input.status)),
      setVariantInventory: protectedProcedure.input(adminInventoryInputSchema).mutation(({ ctx, input }) => setMerchantVariantInventory(ctx.user.id, input.variantId, input.inventoryQty)),
      uploadProductMedia: protectedProcedure.input(merchantProductMediaUploadInputSchema).mutation(({ ctx, input }) => uploadMerchantProductMedia(ctx.user.id, input)),
      bulkUploadProductMedia: protectedProcedure.input(merchantProductMediaBulkUploadInputSchema).mutation(({ ctx, input }) => bulkUploadMerchantProductMedia(ctx.user.id, input)),
      updateProductMedia: protectedProcedure.input(merchantProductMediaUpdateInputSchema).mutation(({ ctx, input }) => updateMerchantProductMedia(ctx.user.id, input)),
      deleteProductMedia: protectedProcedure.input(merchantProductMediaDeleteInputSchema).mutation(({ ctx, input }) => deleteMerchantProductMedia(ctx.user.id, input.mediaId)),
      updateVariant: protectedProcedure.input(merchantVariantUpdateInputSchema).mutation(({ ctx, input }) => updateMerchantVariant(ctx.user.id, input)),
      generateVariantCombinations: protectedProcedure.input(merchantVariantCombinationInputSchema).mutation(({ ctx, input }) => generateMerchantVariantCombinations(ctx.user.id, input)),
      importCatalogCsv: protectedProcedure.input(merchantCatalogCsvImportInputSchema).mutation(({ ctx, input }) => importMerchantCatalogCsv(ctx.user.id, input.csvText)),
      updateCommercialSettings: protectedProcedure.input(merchantCommercialSettingsInputSchema).mutation(({ ctx, input }) => updateCommercialSettings({ userId: ctx.user.id, ...input })),
      updatePaymentProvider: protectedProcedure.input(merchantPaymentProviderInputSchema).mutation(({ ctx, input }) => updateMerchantPaymentProvider({ userId: ctx.user.id, ...input })),
      upsertDeliveryRate: protectedProcedure.input(merchantDeliveryRateInputSchema).mutation(({ ctx, input }) => upsertMerchantDeliveryRate({ userId: ctx.user.id, ...input })),
      upsertTaxRate: protectedProcedure.input(merchantTaxRateInputSchema).mutation(({ ctx, input }) => upsertMerchantTaxRate({ userId: ctx.user.id, ...input })),
      orderOperations: protectedProcedure.input(z.object({ storeId: z.string().min(3).max(64) })).query(({ ctx, input }) => listMerchantOrderOperations(ctx.user.id, input.storeId)),
      monitoring: protectedProcedure.input(z.object({ storeId: z.string().min(3).max(64) })).query(({ ctx, input }) => getMerchantOperationsMonitoring(ctx.user.id, input.storeId)),
      subscriptionInvoices: protectedProcedure.input(z.object({ storeId: z.string().min(3).max(64) })).query(({ ctx, input }) => listMerchantSubscriptionInvoices(ctx.user.id, input.storeId)),
      submitSubscriptionInvoiceReference: protectedProcedure.input(merchantSubscriptionInvoiceReferenceInputSchema).mutation(({ ctx, input }) => submitMerchantSubscriptionInvoiceReference(ctx.user.id, input)),
      reviewPayment: protectedProcedure.input(merchantPaymentReviewInputSchema).mutation(({ ctx, input }) => reviewMerchantPayment({ userId: ctx.user.id, ...input })),
      createShipment: protectedProcedure.input(merchantShipmentInputSchema).mutation(({ ctx, input }) => createMerchantShipment({ userId: ctx.user.id, ...input })),
      resolveReturn: protectedProcedure.input(merchantReturnDecisionInputSchema).mutation(({ ctx, input }) => resolveMerchantReturn({ userId: ctx.user.id, ...input })),
      createRefund: protectedProcedure.input(merchantRefundInputSchema).mutation(({ ctx, input }) => createMerchantRefund({ userId: ctx.user.id, ...input })),
      cancelOrder: protectedProcedure.input(merchantOrderCancellationInputSchema).mutation(({ ctx, input }) => cancelMerchantOrder({ userId: ctx.user.id, ...input })),
      updateShipmentStatus: protectedProcedure.input(merchantShipmentStatusInputSchema).mutation(({ ctx, input }) => updateMerchantShipmentStatus({ userId: ctx.user.id, ...input })),
      resolveRefund: protectedProcedure.input(merchantRefundResolutionInputSchema).mutation(({ ctx, input }) => resolveMerchantRefund({ userId: ctx.user.id, ...input })),
    }),
  }),
});
